[versions]
#android
android-gradle = "7.4.2"
android-material = "1.7.0"
android-lifecycle-viewModel-KTX = "2.5.1"

#androidx
androidx-core = "1.7.0"
androidx-appcompat = "1.5.1"
androidx-constraintlayout = "2.1.4"
androidx-activity-ktx = "1.7.0"
androidx-fragment-ktx = "1.5.4"
androidx-lifecycle-runtime-ktx = "2.4.0.-alpha01"
androidx-navigation = "2.5.3"
androidx-core-splash = "1.0.0"

#kotlin
kotlin = "1.8.10"
kotlin-jvm = "1.8.10"
collections-immutable = "0.3.5"

#test
junit = "4.13.2"
androidx-junit = "1.1.3"
androidx-espresso = "3.4.0"
mockk = "1.13.2"
assertj = "3.20.2"

#ktlint
ktlint = "11.3.1"

#detekt
detekt = "1.22.0"

#DI
hilt = "2.44.2"
hilt-androidX-compiler = "1.0.0"

#Coroutines
coroutines = '1.6.1'

#Network
okhttp = "4.9.3"
retrofit = "2.9.0"
gson = "2.8.9"
mockwebserver = "4.9.0"

#Firebase
gms-google-services = "4.3.15"
firebase-bom = "31.3.0"
firebase-crashlytics-gradle = "2.9.4"

#glide
glide = "4.14.2"

#javax-email
javax_mail = "1.6.2"

#jetpack compose
jetpack-compose = "1.4.3"
jetpack-compose-activity = "1.7.2"
jetpack-compose-viewmodel = "2.6.1"
jetpack-compose-navigation = "2.5.3"
jetpack-compose-hilt-navigation = "1.0.0"
jetpack-compose-coil = "2.4.0"
app-compat-theme-adpater = "0.28.0"

#lottie
lottie = "5.2.0"

#compose-blur
renderscript-intrinsics-replacement-toolkit = "b6363490c3"

serialization = "1.8.10"

[plugins]
#android
application = { id = "com.android.application", version.ref = "android.gradle" }
library = { id = "com.android.library", version.ref = "android.gradle" }

#kotlin
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin.jvm" }

#ktlint
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

#detekt
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }

[libraries]
#android
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android.gradle" }
android-material = { module = "com.google.android.material:material", version.ref = "android-material" }

#androidx
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity-ktx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment-ktx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime-ktx" }
androidx-navigation = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-core-splash = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splash" }

#kotlin
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "collections-immutable" }

#test
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }

#detekt
detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-cli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

#DI
hilt-android-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-androidX-compiler" }

#Coroutine
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "android-lifecycle-viewModel-KTX" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

#Network
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
mock-webserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

#firebase
gms-google-services = { module = "com.google.gms:google-services", version.ref = "gms-google-services" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }

#Glide
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideComplier = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

#javax-mail
javax-mail = { module = "javax.mail:javax.mail-api", version.ref = "javax_mail" }
android-mail = { module = "com.sun.mail:android-mail", version.ref = "javax_mail" }
android-activation = { module = "com.sun.mail:android-activation", version.ref = "javax_mail" }

#Jetpack Compose
jetpack-compose-material = { module = "androidx.compose.material:material", version.ref = "jetpack-compose" }
jetpack-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "jetpack-compose" }
jetpack-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "jetpack-compose" }
jetpack-compose-ui-tooling-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "jetpack-compose" }
jetpack-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "jetpack-compose-activity" }
jetpack-compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "jetpack-compose-viewmodel" }
jetpack-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "jetpack-compose-navigation" }
jetpack-compose-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "jetpack-compose-hilt-navigation" }
jetpack-compose-coil = { module = "io.coil-kt:coil-compose", version.ref = "jetpack-compose-coil" }
app-compat-theme-adpater = { module = "com.google.accompanist:accompanist-themeadapter-appcompat", version.ref = "app-compat-theme-adpater" }

#lottie
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

#compose-blur
renderscript-intrinsics-replacement-toolkit = { module = "com.github.android:renderscript-intrinsics-replacement-toolkit", version.ref = "renderscript-intrinsics-replacement-toolkit" }
