name: Android CI

on:
    push:
        branches: [ "develop" ]
    pull_request:
        branches: [ "develop" ]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: '11'
                  distribution: 'temurin'
                  cache: gradle

            - name: Cache Gradle packages
              uses: actions/cache@v3.0.11
              with:
                path: |
                  ~/.gradle/caches
                  ~/.gradle/wrapper
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
                restore-keys: |
                  ${{ runner.os }}-gradle-

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Add Key Info into local.properties
              run: |
                touch ./local.properties
                echo -e "\nKAKAO_NATIVE_APP_KEY=$KAKAO_NATIVE_APP_KEY" >> ./local.properties
                echo -e "\nOAUTH_CLIENT_ID_NAVER=$OAUTH_CLIENT_ID_NAVER" >> ./local.properties
                cat ./local.properties
              shell: bash
              env:
                KAKAO_NATIVE_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
                OAUTH_CLIENT_ID_NAVER: ${{ secrets.OAUTH_CLIENT_ID_NAVER }}

            - name: Build with Gradle Without Test
              run: ./gradlew build -x test

    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'
            cache: gradle

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Add Key Info into local.properties
          run: |
            touch ./local.properties
            echo -e "\nKAKAO_NATIVE_APP_KEY=$KAKAO_NATIVE_APP_KEY" >> ./local.properties
            echo -e "\nOAUTH_CLIENT_ID_NAVER=$OAUTH_CLIENT_ID_NAVER" >> ./local.properties
            cat ./local.properties
          shell: bash
          env:
            KAKAO_NATIVE_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
            OAUTH_CLIENT_ID_NAVER: ${{ secrets.OAUTH_CLIENT_ID_NAVER }}

        - name: Run unit tests
          run: ./gradlew testDebugUnitTest

        - name: Create android test report
          uses: asadmansr/android-test-report-action@v1.2.0
          if: ${{ always() }}

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: '11'
                  distribution: 'temurin'
                  cache: gradle

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Add Key Info into local.properties
              run: |
                touch ./local.properties
                echo -e "\nKAKAO_NATIVE_APP_KEY=$KAKAO_NATIVE_APP_KEY" >> ./local.properties
                echo -e "\nOAUTH_CLIENT_ID_NAVER=$OAUTH_CLIENT_ID_NAVER" >> ./local.properties
                cat ./local.properties
              shell: bash
              env:
                KAKAO_NATIVE_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
                OAUTH_CLIENT_ID_NAVER: ${{ secrets.OAUTH_CLIENT_ID_NAVER }}

            - name: Cache Gradle packages
              uses: actions/cache@v3.0.11
              with:
                path: |
                  ~/.gradle/caches
                  ~/.gradle/wrapper
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
                restore-keys: |
                  ${{ runner.os }}-gradle-

            - name: Run ktlint
              run: ./gradlew ktlintCheck --stacktrace

            - name: Run detekt
              run: ./gradlew detekt

    alert:
        runs-on: ubuntu-latest
        needs: [build, lint, test]
        steps:
        - name: action-slack
          uses: 8398a7/action-slack@v3.14.0
          with:
            status: ${{ job.status }}
            author_name: THT-Android CI
            fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
            custom_payload: |
              {
                attachments: [{
                  color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                  text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
                }]
              }
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          if: always() # Pick up events even if the job fails or is canceled.
